[supervisord]
nodaemon=true
user=root

[program:fastapi]
command=/usr/local/bin/uvicorn services:app --host 0.0.0.0 --port 8000
directory=/app
autorestart=true
stdout_logfile=/app/fastapi.log
stderr_logfile=/app/fastapi_err.log

[program:gradio]
command=/usr/local/bin/python /app/app.py
directory=/app
autorestart=true
stdout_logfile=/app/gradio.log
stderr_logfile=/app/gradio_err.log